include: package:flutter_lints/flutter.yaml

analyzer:
   language:
      strict-inference: true
      strict-raw-types: true

linter:
   rules:
      file_names: false

      # Qualität
      avoid_print: true
      prefer_const_constructors: true
      prefer_const_literals_to_create_immutables: true
      prefer_final_fields: true
      unnecessary_this: true

      # Flutter
      use_key_in_widget_constructors: true
      sized_box_for_whitespace: true

      # Safety
      always_declare_return_types: true
      cancel_subscriptions: true
      close_sinks: true

      # Async
      unawaited_futures: true
      avoid_void_async: true

      # Style
      prefer_single_quotes: true
      sort_constructors_first: true
